name: docker publish, and deploy

on:
    push:
      branches:
        - master  

jobs:
  build-and-publish:
    name: publish to dockerhub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: almightyzero/recipe-md
          tag_with_ref: true
          add_git_labels: true

  deploy:
    name: deploy
    needs: [build-and-publish]
    runs-on: ubuntu-latest
    steps:
    - name: SSH and deploy node app
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          docker pull almightyzero/recipe-md
          docker stop recipe-md
          docker rm recipe-md
          docker run --name=recipe-md --restart=unless-stopped -p 3001:3000 almightyzero/recipe-md
